#!/usr/bin/env python3
"""Generate native adapters from the workspace agent harness."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import tomllib
from pathlib import Path


# abspath, not resolve: `.agent-harness` is itself a symlink into the config repo, and
# dereferencing it would point WORKSPACE at the repo checkout instead of the workspace.
WORKSPACE = Path(os.path.abspath(__file__)).parent.parent
HARNESS = WORKSPACE / ".agent-harness"
GENERATED = HARNESS / "generated"

ADAPTER_LINKS = {
    WORKSPACE / ".claude" / "agents": "../.agent-harness/generated/claude-agents",
    WORKSPACE / ".claude" / "commands": "../.agent-harness/commands",
    WORKSPACE / ".claude" / "references": "../.agent-harness/references",
    WORKSPACE / ".claude" / "hooks": "../.agent-harness/hooks",
    WORKSPACE / ".claude" / "scripts": "../.agent-harness/scripts",
    WORKSPACE / ".claude" / "inactive": "../.agent-harness/inactive",
    WORKSPACE / ".claude" / "skills": "../.agent-harness/skills",
    WORKSPACE / ".claude" / "GUIDE.md": "../.agent-harness/docs/GUIDE.md",
    WORKSPACE / ".claude" / "SETUP.md": "../.agent-harness/docs/SETUP.md",
    WORKSPACE / ".cursor" / "agents": "../.agent-harness/generated/cursor-agents",
    WORKSPACE / ".cursor" / "commands": "../.agent-harness/commands",
    WORKSPACE / ".cursor" / "skills": "../.agent-harness/skills",
    WORKSPACE / ".codex" / "agents": "../.agent-harness/generated/codex-agents",
    WORKSPACE / ".agents" / "skills": "../.agent-harness/generated/codex-skills",
    GENERATED / "codex-skills" / "automate-ui": "../../skills/automate-ui",
    GENERATED / "codex-skills" / "triage-ui": "../../skills/triage-ui",
}


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    if not text.startswith("---\n"):
        return {}, text.strip()
    _, raw, body = text.split("---\n", 2)
    fields: dict[str, str] = {}
    current: str | None = None
    for line in raw.splitlines():
        match = re.match(r"^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$", line)
        if match:
            current = match.group(1)
            value = match.group(2).strip()
            fields[current] = "" if value in {">", "|"} else value
        elif current and line.startswith((" ", "\t")):
            fields[current] = f"{fields[current]} {line.strip()}".strip()
    return fields, body.strip()


def compact_description(value: str, body: str, name: str) -> str:
    if value:
        return re.sub(r"\s+", " ", value).strip()
    for line in body.splitlines():
        candidate = line.strip().lstrip("#").strip()
        if candidate and not candidate.startswith(("```", "---")):
            return re.sub(r"\s+", " ", candidate)[:300]
    return f"Run the {name.replace('-', ' ')} workspace workflow."


def render_codex_agents() -> dict[Path, str]:
    rendered: dict[Path, str] = {}
    for source in sorted((HARNESS / "agents").glob("*.md")):
        fields, body = parse_frontmatter(source.read_text())
        name = fields.get("name") or source.stem
        description = compact_description(fields.get("description", ""), body, name)
        instructions = (
            "These instructions are shared across agent providers. Follow the workspace "
            "AGENTS.md contract and use provider-native tools available in this session.\n\n"
            + body
        )
        content = (
            "# Generated by .agent-harness/sync.py; edit .agent-harness/agents/"
            f"{source.name} instead.\n"
            f"name = {json.dumps(name, ensure_ascii=False)}\n"
            f"description = {json.dumps(description, ensure_ascii=False)}\n"
            f"developer_instructions = {json.dumps(instructions, ensure_ascii=False)}\n"
        )
        tomllib.loads(content)
        rendered[GENERATED / "codex-agents" / f"{source.stem}.toml"] = content
    return rendered


def render_markdown_agents() -> dict[Path, str]:
    rendered: dict[Path, str] = {}
    metadata_path = HARNESS / "provider-agent-metadata.json"
    metadata = json.loads(metadata_path.read_text()) if metadata_path.exists() else {}
    claude_metadata = metadata.get("claude", {})

    for source in sorted((HARNESS / "agents").glob("*.md")):
        text = source.read_text()
        rendered[GENERATED / "cursor-agents" / source.name] = text

        fields = claude_metadata.get(source.stem, {})
        additions = "".join(
            f"{key}: {fields[key]}\n" for key in ("tools", "model") if fields.get(key)
        )
        if additions and text.startswith("---\n"):
            marker = text.find("---\n", 4)
            if marker == -1:
                raise ValueError(f"unclosed frontmatter: {source}")
            text = text[:marker] + additions + text[marker:]
        rendered[GENERATED / "claude-agents" / source.name] = text
    return rendered


def render_command_skills() -> dict[Path, str]:
    rendered: dict[Path, str] = {}
    native_skills = {"automate-ui", "triage-ui"}
    for source in sorted((HARNESS / "commands").glob("*.md")):
        if source.stem in native_skills:
            continue
        fields, body = parse_frontmatter(source.read_text())
        description = compact_description(fields.get("description", ""), body, source.stem)
        body = body.replace("$ARGUMENTS", "the user's supplied arguments")
        content = (
            "---\n"
            f"name: {source.stem}\n"
            f"description: {json.dumps(description, ensure_ascii=False)}\n"
            "disable-model-invocation: true\n"
            "---\n\n"
            "# Generated workspace workflow\n\n"
            "Follow this workflow directly, or delegate to the matching specialized agent "
            "when the current provider supports custom agents.\n\n"
            f"{body}\n"
        )
        rendered[GENERATED / "codex-skills" / source.stem / "SKILL.md"] = content
    return rendered


def render_mcp() -> dict[Path, str]:
    source = HARNESS / "mcp" / "servers.json"
    if not source.exists():
        return {}
    data = json.loads(source.read_text())
    common = data.get("common", {})
    providers = data.get("providers", {})

    def merged(provider: str) -> dict[str, object]:
        result = {name: dict(config) for name, config in common.items()}
        for name, config in providers.get(provider, {}).items():
            result[name] = {**result.get(name, {}), **config}
        return result

    claude = {"mcpServers": merged("claude")}
    cursor = {"mcpServers": merged("cursor")}
    rendered = {
        WORKSPACE / ".mcp.json": json.dumps(claude, indent=2, ensure_ascii=False) + "\n",
        WORKSPACE / ".cursor" / "mcp.json": json.dumps(cursor, indent=2, ensure_ascii=False) + "\n",
    }

    codex_servers = merged("codex")
    lines = ["# Generated by .agent-harness/sync.py; edit mcp/servers.json instead."]
    for name, config in sorted(codex_servers.items()):
        lines.append(f"\n[mcp_servers.{name}]")
        if "url" in config:
            lines.append(f"url = {json.dumps(config['url'])}")
        elif "command" in config:
            lines.append(f"command = {json.dumps(config['command'])}")
            if config.get("args"):
                lines.append(f"args = {json.dumps(config['args'])}")
    codex = "\n".join(lines) + "\n"
    tomllib.loads(codex)
    rendered[WORKSPACE / ".codex" / "config.toml"] = codex
    return rendered


def desired_files() -> dict[Path, str]:
    result: dict[Path, str] = {}
    result.update(render_markdown_agents())
    result.update(render_codex_agents())
    result.update(render_command_skills())
    result.update(render_mcp())
    return result


def sync_adapter_links(check: bool) -> tuple[list[Path], list[Path]]:
    stale: list[Path] = []
    blocked: list[Path] = []
    for path, target in ADAPTER_LINKS.items():
        if path.is_symlink() and str(path.readlink()) == target:
            continue
        stale.append(path)
        if check:
            continue
        if path.exists() and not path.is_symlink():
            blocked.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.is_symlink():
            path.unlink()
        path.symlink_to(target)
    return stale, blocked


def broken_links() -> list[Path]:
    """Symlinks whose target does not resolve.

    A link can match its expected target string exactly and still be dead, so the
    string comparison above cannot catch this. sync.py does not repair these: the
    app-skill targets live outside the harness, so a wrong one is an authoring error.
    """
    candidates = list(ADAPTER_LINKS)
    for directory in (HARNESS / "skills", GENERATED / "codex-skills"):
        if directory.exists():
            candidates.extend(child for child in directory.iterdir() if child.is_symlink())
    return [path for path in candidates if path.is_symlink() and not path.exists()]


def sync(check: bool) -> int:
    files = desired_files()
    stale: list[Path] = []
    link_stale, blocked = sync_adapter_links(check)
    stale.extend(link_stale)
    for path, content in files.items():
        if not path.exists() or path.read_text() != content:
            stale.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
                if path in {WORKSPACE / ".mcp.json", WORKSPACE / ".cursor" / "mcp.json"}:
                    path.chmod(0o600)

    for directory, suffix in (
        (GENERATED / "codex-agents", "*.toml"),
        (GENERATED / "claude-agents", "*.md"),
        (GENERATED / "cursor-agents", "*.md"),
    ):
        expected_agents = {p for p in files if p.parent == directory}
        if directory.exists():
            for path in directory.glob(suffix):
                if path not in expected_agents:
                    stale.append(path)
                    if not check:
                        path.unlink()

    command_names = {
        p.parent.name
        for p in files
        if p.name == "SKILL.md" and p.parent.parent == GENERATED / "codex-skills"
    }
    codex_skills = GENERATED / "codex-skills"
    codex_skills.mkdir(parents=True, exist_ok=True)
    for path in codex_skills.iterdir():
        if path.is_dir() and not path.is_symlink() and path.name not in command_names:
            marker = path / "SKILL.md"
            if marker.exists() and "# Generated workspace workflow" in marker.read_text():
                stale.append(path)
                if not check:
                    shutil.rmtree(path)

    broken = broken_links()
    if stale or broken:
        verb = "stale" if check else "updated"
        for path in sorted(set(stale)):
            print(f"{verb}: {path.relative_to(WORKSPACE)}")
        for path in blocked:
            print(f"blocked: {path.relative_to(WORKSPACE)} is not a symlink; preserved")
        for path in sorted(set(broken)):
            print(f"broken: {path.relative_to(WORKSPACE)} -> {path.readlink()}")
        return 1 if check or blocked or broken else 0
    print("agent harness adapters are current")
    return 0


if __name__ == "__main__":
    if not (WORKSPACE / ".claude").is_dir():
        raise SystemExit(
            f"{WORKSPACE} is not the workspace root — it has no .claude directory.\n"
            "Invoke this through the workspace symlink, not the config repo path:\n"
            "  cd <workspace> && python3 .agent-harness/sync.py"
        )
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="report drift without writing")
    args = parser.parse_args()
    raise SystemExit(sync(args.check))
